### ISSUE TITLE
Read only database when adding custom server

### ISSUE THREAD

**Issue by JmzTaylor** [vitodeploy/vito#147]
Using any other provider it will provision a server without issue.  When I use custom server, after entering all the details it does not provision and this is constantly repeated in laravel.log

```
[previous exception] [object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 8 attempt to write a readonly database at /home/vito/vito/vendor/laravel/framework/src/Illuminate/Database/Connection.php:612)
[stacktrace]
#0 /home/vito/vito/vendor/laravel/framework/src/Illuminate/Database/Connection.php(612): PDOStatement->execute()
#1 /home/vito/vito/vendor/laravel/framework/src/Illuminate/Database/Connection.php(816): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#2 /home/vito/vito/vendor/laravel/framework/src/Illuminate/Database/Connection.php(783): Illuminate\\Database\\Connection->runQueryCallback()
#3 /home/vito/vito/vendor/laravel/framework/src/Illuminate/Database/Connection.php(600): Illuminate\\Database\\Connection->run()
#4 /home/vito/vito/vendor/laravel/framework/src/Illuminate/Database/Connection.php(552): Illuminate\\Database\\Connection->affectingStatement()
#5 /home/vito/vito/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3560): Illuminate\\Database\\Connection->update()
#6 /home/vito/vito/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(336): Illuminate\\Database\\Query\\Builder->update()
#7 /home/vito/vito/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(321): Illuminate\\Queue\\DatabaseQueue->markJobAsReserved()
#8 /home/vito/vito/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(225): Illuminate\\Queue\\DatabaseQueue->marshalJob()
#9 /home/vito/vito/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(30): Illuminate\\Queue\\DatabaseQueue->Illuminate\\Queue\\{closure}()
#10 /home/vito/vito/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(223): Illuminate\\Database\\Connection->transaction()
#11 /home/vito/vito/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(349): Illuminate\\Queue\\DatabaseQueue->pop()
#12 /home/vito/vito/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(363): Illuminate\\Queue\\Worker->Illuminate\\Queue\\{closure}()
#13 /home/vito/vito/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(162): Illuminate\\Queue\\Worker->getNextJob()
#14 /home/vito/vito/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(137): Illuminate\\Queue\\Worker->daemon()
#15 /home/vito/vito/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(120): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#16 /home/vito/vito/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#17 /home/vito/vito/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#18 /home/vito/vito/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#19 /home/vito/vito/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#20 /home/vito/vito/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#21 /home/vito/vito/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#22 /home/vito/vito/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#23 /home/vito/vito/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#24 /home/vito/vito/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#25 /home/vito/vito/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#26 /home/vito/vito/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#27 /home/vito/vito/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#28 /home/vito/vito/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#29 {main}
```

**Comment by JmzTaylor** [comment]
So this is on a fresh install.  The way I got around this was to chmod 777 database.sqlite which isn't ideal but it fixed the issue.  Had to restart the queue also.

**Comment by saeedvaziry** [comment]
Try this command

```
sudo chown -R vito:vito /home/vito/YOUR-VITO-DOMAIN \
    && chmod -R 755 /home/vito/YOUR-VITO-DOMAIN/storage /home/vito/YOUR-VITO-DOMAIN/bootstrap/cache
```

**Comment by saeedvaziry** [comment]
Closing due to inactivity
