### ISSUE TITLE
Site with Bitbucket repository creation error.

### ISSUE THREAD

**Issue by johnwilson** [vitodeploy/vito#82]
Hi, I keep getting an error when creating a site with a Bitbucket repository. I've created a repository level access token and I'm able to view repository information using Postman and the token. However the site creation fails with the following error in Vito's logs:
```
production.ERROR: install-site-error {"error":"App\\Exceptions\\FailedToDeployGitKey: This API is not accessible by this authentication mechanism in /home/vito/xxxx/app/SourceControlProviders/Bitbucket.php:120
```

**Comment by saeedvaziry** [comment]
Hi @johnwilson, Try to increase the permissions of the token as Vito needs to create a deployment key and add the public key of your server to the source control.

**Comment by johnwilson** [comment]
Hi @saeedvaziry, thanks for the quick response. Can you confirm if a repository level access token is sufficient? I enabled all the scopes but still getting the same error.

**Comment by saeedvaziry** [comment]
I will try to reproduce this

**Comment by saeedvaziry** [comment]
I managed to reproduce the issue and here is the stack trace.

```
{
  "exception": "[object] (App\\Exceptions\\FailedToDeployGitKey(code: 0): This API is not accessible by this authentication mechanism at /home/vito/vito.team/app/SourceControlProviders/Bitbucket.php:120)
[stacktrace]
#0 /home/vito/vito.team/app/Jobs/Site/DeployKey.php(39): App\\SourceControlProviders\\Bitbucket->deployKey()
#1 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\Site\\DeployKey->handle()
#2 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#4 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#5 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#6 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#7 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#8 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#10 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\\Bus\\Dispatcher->dispatchNow()
#11 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#12 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(126): Illuminate\\Pipeline\\Pipeline->then()
#14 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#15 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#16 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(439): Illuminate\\Queue\\Jobs\\Job->fire()
#17 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(389): Illuminate\\Queue\\Worker->process()
#18 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(176): Illuminate\\Queue\\Worker->runJob()
#19 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(138): Illuminate\\Queue\\Worker->daemon()
#20 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(121): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#21 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#22 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#23 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#24 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#25 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#26 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Console/Command.php(208): Illuminate\\Container\\Container->call()
#27 /home/vito/vito.team/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute()
#28 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Console/Command.php(178): Symfony\\Component\\Console\\Command\\Command->run()
#29 /home/vito/vito.team/vendor/symfony/console/Application.php(1040): Illuminate\\Console\\Command->run()
#30 /home/vito/vito.team/vendor/symfony/console/Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand()
#31 /home/vito/vito.team/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun()
#32 /home/vito/vito.team/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#33 /home/vito/vito.team/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#34 {main}
"
}
```

**Comment by saeedvaziry** [comment]
@johnwilson fixed the bug. The issue won't be exist on version 1.0.0 release.

I changed the authentication mechanism for Bitbucket so on version 1.x you will need to create a new credentials for Bitbucket.
